Django-EmployeeCRUD/mywebapps/crudwebapp/urls.py
"""crudwebapp URL Configuration."""
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('departments/', views.departments, name='department'),
    path('add_department/', views.add_department, name='department add'),
    path(
        'edit_department/<int:department_id>/',
        views.edit_department,
        name='department edit'
    ),
    path(
        'update_department/<int:department_id>',
        views.update_department,
        name='department update'
    ),
    path(
        'delete_department/<int:department_id>/',
        views.delete_department,
        name='department delete'
    ),
    path('employees/', views.employees, name='employee'),
    path(
        'edit_employee/<int:employee_id>/',
        views.edit_employee,
        name='employee edit'
    ),
    path(
        'update_employee/<int:employee_id>',
        views.update_employee,
        name='employee update'
    ),
    path('add_employee/', views.add_employee, name='employee add'),
    path(
        'delete_employee/<int:employee_id>/',
        views.delete_employee,
        name='employee delete'
    ),
    path('login/', views.authenticate_user, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('home/', views.home_page, name='home')
]

Django-EmployeeCRUD/mywebapps/mywebapps/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('crudwebapp.urls')),
    path('admin/', admin.site.urls),
]

Django-EmployeeCRUD/mywebapps/crudwebapp/models.py
"""Database models."""
from django.db import models
from .utils import ChoiceEnum


# Create your models here.
class Department(models.Model):
    """Department model."""
    department_id = models.AutoField(primary_key=True, null=False)
    name = models.CharField(max_length=255, null=False)

    def __str__(self):
        return "(department_id=%s, name='%s')" % (
            self.department_id, self.name)


class GenderChoice(ChoiceEnum):
    """Enumeration for gender choice for employee model."""
    male = 'Male'
    female = 'Female'


class Employee(models.Model):
    """Employee model."""
    employee_id = models.AutoField(primary_key=True, null=False)
    name = models.CharField(max_length=255, null=False)
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        null=False
    )
    date_of_join = models.DateField()
    gender = models.CharField(
        max_length=6,
        choices=GenderChoice.choices(),
        default=GenderChoice.male,
        null=False
    )
    address = models.CharField(max_length=1000, null=True)
    salary = models.DecimalField(max_digits=10, decimal_places=2, null=False)

    def __str__(self):
        return "(employee_id=%s, name='%s', department_id=%s, " \
            "date_of_joining='%s', gender='%s', address='%s', " \
            "salary=%s)" % (self.employee_id, self.name, self.department,
                            self.date_of_join, self.gender, self.address,
                            self.salary)

Django-EmployeeCRUD/mywebapps/crudwebapp/forms.py
from django import forms
from .models import Department, Employee


class DepartmentForm(forms.ModelForm):
    """Department form for Add and Edit operations."""
    class Meta:
        model = Department
        fields = "__all__"


class EmployeeForm(forms.ModelForm):
    """Employee form for Add and Edit operations."""
    class Meta:
        model = Employee
        fields = "__all__"

Django-EmployeeCRUD/mywebapps/crudwebapp/views.py
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth import authenticate, login, logout
from .models import Department, Employee, GenderChoice
from .forms import DepartmentForm, EmployeeForm


# Create your views here.
def index(request):
    """Index view.
    :param request: Obj - Request.
    :return: str - HttpResponse response.
    """
    if is_authenticated(request):
        return redirect('/home')
    return render(request, 'login.html')


def departments(request):
    """Show departments detail.
    :param request: Obj - Request.
    :return: Render to department view.
    """
    if not is_authenticated(request):
        return redirect('/login')
    department_list = Department.objects.all()
    return render(
        request, 'departments.html', {'departments': department_list})


def add_department(request):
    """Add department.
    :param request: Obj - Request.
    :return: Renders to departments view on saved or add department page.
    """
    if not is_authenticated(request):
        return redirect('/login')
    if request.method == 'POST':
        form = DepartmentForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/departments')
            except:
                pass
    else:
        form = DepartmentForm()
    return render(
        request, 'department_add.html', {'form': form})


def edit_department(request, department_id):
    """Edit department.
    :param request: Obj - Request.
    :param department_id: int - Unique identification of department.
    :return: Render to edit department page.
    """
    if not is_authenticated(request):
        return redirect('/login')
    department = Department.objects.get(department_id=department_id)
    return render(
        request, 'department_edit.html', {'department': department})


def update_department(request, department_id):
    """Update department.
    :param request: Obj - Request.
    :param department_id: int - Unique identification of department.
    :return: Renders to departments view on update or edit department page.
    """
    if not is_authenticated(request):
        return redirect('/login')
    department = Department.objects.get(department_id=department_id)
    form = DepartmentForm(request.POST, instance=department)
    if form.is_valid():
        form.save()
        return redirect('/departments')
    return render(
        request, 'department_edit.html', {'department': department})


def delete_department(request, department_id):
    """Delete department.
    :param request: Obj - Request.
    :param department_id: int - Unique identification of department.
    :return: Renders to departments view on delete.
    """
    if not is_authenticated(request):
        return redirect('/login')
    department = Department.objects.get(department_id=department_id)
    department.delete()
    return redirect('/departments')


def employees(request):
    """Show employees detail.
    :param request: Obj - Request.
    :return: Render to employee view.
    """
    if not is_authenticated(request):
        return redirect('/login')
    employee_list = Employee.objects.all()
    return render(
        request, 'employees.html', {'employees': employee_list})


def add_employee(request):
    """Add employee.
    :param request: Obj - Request.
    :return: Renders to employees view on saved or add employee page.
    """
    if not is_authenticated(request):
        return redirect('/login')
    department_list = Department.objects.all()
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        print(form)
        if form.is_valid():
            try:
                form.save()
                return redirect('/employees')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(
        request, 'employee_add.html',
        {'form': form, 'departments': department_list})


def edit_employee(request, employee_id):
    """Edit employee.
    :param request: Obj - Request.
    :param employee_id: int - Unique identification of employee.
    :return: Render to edit employee page.
    """
    if not is_authenticated(request):
        return redirect('/login')
    department_list = Department.objects.all()
    employee = Employee.objects.get(employee_id=employee_id)
    return render(
        request, 'employee_edit.html',
        {'employee': employee,
         'departments': department_list,
         'gender_choices':
             [GenderChoice.choices()[0][0], GenderChoice.choices()[1][0]]})


def update_employee(request, employee_id):
    """Update employee.
    :param request: Obj - Request.
    :param employee_id: int - Unique identification of employee.
    :return: Renders to employees view on update or edit employee page.
    """
    if not is_authenticated(request):
        return redirect('/login')
    department_list = Department.objects.all()
    employee = Employee.objects.get(employee_id=employee_id)
    form = EmployeeForm(request.POST, instance=employee)
    if form.is_valid():
        form.save()
        return redirect('/employees')
    return render(
        request, 'employee_edit.html',
        {'employee': employee,
         'departments': department_list,
         'gender_choices':
             [GenderChoice.choices()[0][0], GenderChoice.choices()[1][0]]})


def delete_employee(request, employee_id):
    """Delete employee.
    :param request: Obj - Request.
    :param employee_id: int - Unique identification of department.
    :return: Renders to employees view on delete.
    """
    if not is_authenticated(request):
        return redirect('/login')
    employee = Employee.objects.get(employee_id=employee_id)
    employee.delete()
    return redirect('/employees')


def authenticate_user(request):
    """Authenticate user.
    :param request: Obj - Request.
    :return: Renders to home page otherwise login page.
    """
    if is_authenticated(request):
        return redirect('/home')
    username = password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None and user.is_active:
            # login(request, user)
            request.session['member_id'] = username
            return redirect('/home')
    return render(request, 'login.html')


def log_out(request):
    """Logged out and terminate the session of user.
    :param request: Obj - Request.
    :return: Renders to logout page.
    """
    # logout(request)
    try:
        del request.session['member_id']
    except KeyError:
        pass
    return render_to_response('logout.html')


def home_page(request):
    """Redirects to home page.
    :param request: Obj - Request.
    :return: Renders to the home page.
    """
    if not is_authenticated(request):
        return redirect('/login')
    return render(request, 'home.html')


def is_authenticated(request):
    """Check user session in exists.
    :param request: Obj - Request.
    :return: bool - True if session exists else False.
    """
    try:
        request.session['member_id']
    except KeyError:
        return False
    return True

Django-EmployeeCRUD/mywebapps/crudwebapp/templates/department_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Department Add</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
</head>
<body>
    <center><h1>Add Department Details</h1></center>
    <hr />
    <div align="center">
        <form method="POST" name ="add_form" action="/add_department/" class="form-align">
            {% csrf_token %}
            <label>Department Name:</label>
            {{ form.name }}
            <br /><br />
            <center><button type="submit" class="link_button form-button">Submit</button></center>
        </form>
    </div>
</body>
</html>

Django-EmployeeCRUD/mywebapps/crudwebapp/templates/department_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Department Edit</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
</head>
<body>
    <center><h1>Update Department Details</h1></center>
    <hr />
    <div align="center">
        <form method="POST" name ="edit_form" action="/update_department/{{ department.department_id }}" class="form-align">
            {% csrf_token %}
            <label>Department Name:</label>
            <input type="text" name="name" id="department_name" value="{{ department.name }}" />
            <br /><br />
            <center><button type="submit" class="link_button form-button">Submit</button></center>
        </form>
    </div>
</body>
</html>

Django-EmployeeCRUD/mywebapps/crudwebapp/templates/departments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Departments</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
</head>
<body>
<center><h1>Departments</h1></center>
<hr />
<table>
    <thead>
    <tr>
        <th>Department ID</th>
        <th>Department Name</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% if departments %}
        {% for department in departments %}
            <tr>
                <td>{{ department.department_id }}</td>
                <td>{{ department.name }}</td>
                <td>
                    <a href="/edit_department/{{ department.department_id }}" class="link_button_action"><span>Edit</span></a>
                    <a href="/delete_department/{{ department.department_id }}" class="link_button_action">Delete</a>
                </td>
            </tr>
        {% endfor %}
    {% else %}
        <tr><td colspan="3"><center>No records found!</center></td></tr>
    {% endif %}
    </tbody>
</table>
<br>
<br>
<center><a href="/add_department" class="link_button">Add New Record</a></center>
</body>
</html>

Django-EmployeeCRUD/mywebapps/crudwebapp/templates/employee_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Add</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $( function() {
            $( "#id_date_of_join" ).datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: 'yy-mm-dd'
            });
        });
    </script>
</head>
<body>
    <center><h1>Add Employee Details</h1></center>
    <hr />
    <div align="center">
        <form method="POST" name="add_form" id="add_form" action="/add_employee/" class="form-align">
            {% csrf_token %}
            <label>Employee Name:</label>
            {{ form.name }}
            <br /><br />

            <label>Department:</label>
            <select name="department" id="id_department">
                {% for department in departments %}
                    <option value="{{ department.department_id }}">{{ department.name }}</option>
                {% endfor %}
            </select>
            <br /><br />

            <label>Date of join:</label>
            {{ form.date_of_join }}
            <br /><br />

            <label>Gender:</label>
            {{ form.gender }}
            <br /><br />

            <label>Address:</label>
            {{ form.address }}
            <br /><br />

            <label>Salary:</label>
            {{ form.salary }}
            <br /><br />
            <center><button type="submit" class="link_button form-button">Submit</button></center>
        </form>
    </div>
</body>
</html>

Django-EmployeeCRUD/mywebapps/crudwebapp/templates/employee_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Edit</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $( function() {
            $( "#id_date_of_join" ).datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: 'yy-mm-dd'
            });
        });
    </script>
</head>
<body>
    <center><h1>Update Employee Details</h1></center>
    <hr />
    <div align="center">
        <form method="POST" name ="edit_form" id="edit_form" action="/update_employee/{{ employee.employee_id }}" class="form-align">
            {% csrf_token %}
            <label>Employee Name:</label>
            <input type="text" name="name" id="id_name" value="{{ employee.name }}" />
            <br /><br />

            <label>Department:</label>
            <select name="department" id="id_department">
                {% for department in departments %}
                    {% if department.department_id == employee.department_id %}
                        <option value="{{ department.department_id }}" selected="selected">{{ department.name }}</option>
                    {% else %}
                        <option value="{{ department.department_id }}">{{ department.name }}</option>
                    {% endif %}
                {% endfor %}
            </select>
            <br /><br />

            <label>Date of join:</label>
            <input type="text" name="date_of_join" id="id_date_of_join" value="{{ employee.date_of_join|date:'Y-m-d' }}" />
            <br /><br />

            <label>Gender:</label>
            <select name="gender" id="id_gender">
                {% for gender in gender_choices %}
                    {% if gender == employee.gender %}
                        <option value="{{ gender }}" selected="selected">{{ gender|capfirst }}</option>
                    {% else %}
                        <option value="{{ gender }}">{{ gender|capfirst }}</option>
                    {% endif %}
                {% endfor %}
            </select>
            <br /><br />

            <label>Address:</label>
            <input type="text" name="address" id="id_address" value="{{ employee.address }}" />
            <br /><br />

            <label>Salary:</label>
            <input type="number" name="salary" id="id_salary" value="{{ employee.salary }}" />
            <br /><br />
            <center><button type="submit" class="link_button form-button">Submit</button></center>
        </form>
    </div>
</body>
</html>

Django-EmployeeCRUD/mywebapps/crudwebapp/templates/employees.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employees</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
</head>
<body>
<center><h1>Employees</h1></center>
<hr />
<table>
    <thead>
    <tr>
        <th>Employee ID</th>
        <th>Employee Name</th>
        <th>Department</th>
        <th>Date of Join</th>
        <th>Gender</th>
        <th>Address</th>
        <th>Salary</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% if employees %}
        {% for employee in employees %}
            <tr>
                <td>{{ employee.employee_id }}</td>
                <td>{{ employee.name }}</td>
                <td>{{ employee.department.name }}</td>
                <td>{{ employee.date_of_join|date:"Y-m-d" }}</td>
                <td>{{ employee.gender|capfirst }}</td>
                <td>{{ employee.address }}</td>
                <td>{{ employee.salary }}</td>
                <td>
                    <a href="/edit_employee/{{ employee.employee_id }}" class="link_button_action"><span>Edit</span></a>
                    <a href="/delete_employee/{{ employee.employee_id }}" class="link_button_action">Delete</a>
                </td>
            </tr>
        {% endfor %}
    {% else %}
        <tr><td colspan="8"><center>No records found!</center></td></tr>
    {% endif %}
    </tbody>
</table>
<br>
<br>
<center><a href="/add_employee" class="link_button">Add New Record</a></center>
</body>
</html>

Django-EmployeeCRUD/mywebapps/crudwebapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <center><h1>Home</h1></center>
    <hr />
    <p align="right"><a href="{% url 'logout' %}" style="text-decoration: none;">Log out</a></p>
    <div align="center">
        <div><a href="/departments/" style="text-decoration: none;">Departments</a></div>
        <br />
        <div><a href="/employees/" style="text-decoration: none;">Employees</a></div>
    </div>
</body>
</html>

Django-EmployeeCRUD/mywebapps/crudwebapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
</head>
<body>
    <center><h1>Login</h1></center>
    <hr />
    <div align="center">
        <form name="LoginForm" action="/login/" method="post" class="form-align">
            {% csrf_token %}
            <div>
                <label>Username</label>
                <div>
                    <input type="text" id="username" name="username"  placeholder="Username">
                </div>
            </div>
            <div>
                <label>Password</label>
                <div>
                    <input type="password" name="password" id="password" placeholder="Password">
                </div>
            </div>
            <div>
                <div>
                    <button type="submit" class="link_button form-button">Login</button>
                </div>
            </div>
        </form>
    </div>
</body>
</html>

Django-EmployeeCRUD/mywebapps/crudwebapp/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
    <center><h2>Logged out</h2></center>
    <div align="center">
        <p>You have been successfully logged out.</p>
        <p><a href="{% url 'login' %}" style="text-decoration: none;">Log in</a> again.</p>
    </div>
</body>
</html>